### ISSUE TITLE
React js old version

### ISSUE THREAD

**Issue by alexey-gorshkov** [hanford/react-scroll-listen#3]
Please update React Version

I get warning npm WARN react-scroll-listen@0.6.2 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by hanford** [comment]
No longer using this plugin.

I'd actually recommend looking at `intersection-observers` as scroll listening is really bad for browser performance.

There are some really nice / well maintained react intersection observer components, too.

[Intersection observer docs](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by alexey-gorshkov** [comment]
Thanks!
